version: "3.9"

services:
  rifa-api:
    build: .
    container_name: rifa-api

    env_file:
      - .env

    expose:
      - "3333"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rifa.rule=Host(`rifa.minklab.cloud`)"
      - "traefik.http.routers.rifa.entrypoints=websecure"
      - "traefik.http.routers.rifa.tls.certresolver=le"
      - "traefik.http.services.rifa.loadbalancer.server.port=3333"

    networks:
      - web

    restart: unless-stopped

networks:
  web:
    external: true
